; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -gvn-enable-min-finding-select-pattern -passes=gvn -S < %s | FileCheck %s

declare void @external_function(ptr)

; Negative test: Select not in a loop.
define void @test_not_in_loop(ptr %arr) {
; CHECK-LABEL: define void @test_not_in_loop(
; CHECK-SAME: ptr [[ARR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[ARR]], align 4
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 1
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    ret void
;
entry:
  %gep1 = getelementptr float, ptr %arr, i32 0
  %load1 = load float, ptr %gep1
  %sext = sext i32 1 to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  ret void
}

; Negative test: Loop without preheader (multiple entry points).
define void @test_no_preheader(ptr %arr, i32 %n, i1 %cond) {
; CHECK-LABEL: define void @test_no_preheader(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP:.*]], label %[[OTHER_ENTRY:.*]]
; CHECK:       [[OTHER_ENTRY]]:
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ 0, %[[OTHER_ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[I]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %cond, label %loop, label %other_entry

other_entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ 0, %other_entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %i to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Condition is not a CmpInst.
define void @test_condition_not_cmp(ptr %arr, i32 %n, i1 %bool) {
; CHECK-LABEL: define void @test_condition_not_cmp(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]], i1 [[BOOL:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[I]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %i to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %sel = select i1 %bool, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Not both operands are loads (constant RHS).
define void @test_not_both_loads(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_not_both_loads(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], 0.000000e+00
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float 0.000000e+00
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %cmp = fcmp olt float %load1, 0.0
  %sel = select i1 %cmp, float %load1, float 0.0
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Load doesn't match GEP(GEP(...))nested pattern.
define void @test_wrong_gep_pattern(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_wrong_gep_pattern(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  ; Simple GEP, not nested GEP(GEP(...))
  %gep2 = getelementptr float, ptr %arr, i32 %i
  %load2 = load float, ptr %gep2
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: ZExt instead of SExt.
define void @test_no_sext(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_no_sext(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[I]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[ZEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %zext = zext i32 %i to i64
  %gep2 = getelementptr float, ptr %arr, i64 %zext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: SExt with wrong types (i16->i32 instead of i32->i64).
define void @test_wrong_sext_types(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_wrong_sext_types(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[I16:%.*]] = trunc i32 [[I]] to i16
; CHECK-NEXT:    [[SEXT:%.*]] = sext i16 [[I16]] to i32
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i32 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %i16 = trunc i32 %i to i16
  %sext = sext i16 %i16 to i32
  %gep2 = getelementptr float, ptr %arr, i32 %sext
  %gep3 = getelementptr i8, ptr %gep2, i32 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: IndexVal is a constant, not a PHI node.
define void @test_index_is_constant(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_index_is_constant(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[GEP2_PHI_TRANS_INSERT:%.*]] = getelementptr float, ptr [[ARR]], i64 5
; CHECK-NEXT:    [[LOAD2_PRE:%.*]] = load float, ptr [[GEP2_PHI_TRANS_INSERT]], align 4
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2_PRE]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2_PRE]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]

  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  ; IndexVal is a constant (5), not a PHI node!
  %sext = sext i32 5 to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Initial min index value is not 1.
define void @test_initial_index_not_one(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_initial_index_not_one(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[I]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  ; Initial value is 0, not 1!
  %min.idx = phi i32 [ 0, %entry ], [ %min.idx.next, %loop ]

  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %min.idx to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %min.idx.next = select i1 %cmp, i32 %i, i32 %min.idx
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Pattern recognized but hoisting not safe due to aliasing store in loop.
define void @test_aliasing_store_in_loop(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_aliasing_store_in_loop(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[STORE_GEP:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    store float 0.000000e+00, ptr [[STORE_GEP]], align 4
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float 0.000000e+00, [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float 0.000000e+00, float [[LOAD2]]
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[I]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]

  ; This store aliases with the loads, preventing hoisting.
  %store.gep = getelementptr float, ptr %arr, i32 %i
  store float 0.0, ptr %store.gep

  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %min.idx to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %min.idx.next = select i1 %cmp, i32 %i, i32 %min.idx
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Pattern recognized but BasePtr is not loop invariant.
define void @test_non_invariant_base_ptr(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_non_invariant_base_ptr(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[BASE_PTR:%.*]] = phi ptr [ [[ARR]], %[[ENTRY]] ], [ [[BASE_PTR_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[BASE_PTR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[BASE_PTR]], i64 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[I]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[BASE_PTR_NEXT]] = getelementptr float, ptr [[BASE_PTR]], i32 1
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]
  ; Base pointer changes each iteration - not loop invariant!
  %base.ptr = phi ptr [ %arr, %entry ], [ %base.ptr.next, %loop ]

  %gep1 = getelementptr float, ptr %base.ptr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %min.idx to i64
  %gep2 = getelementptr float, ptr %base.ptr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %min.idx.next = select i1 %cmp, i32 %i, i32 %min.idx
  %base.ptr.next = getelementptr float, ptr %base.ptr, i32 1
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: Pattern recognized but may-alias call in loop.
define void @test_may_alias_call_in_loop(ptr %arr, i32 %n) {
; CHECK-LABEL: define void @test_may_alias_call_in_loop(
; CHECK-SAME: ptr [[ARR:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @external_function(ptr [[ARR]])
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr float, ptr [[ARR]], i32 [[I]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr float, ptr [[ARR]], i64 [[SEXT]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[LOAD1]], [[LOAD2]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], float [[LOAD1]], float [[LOAD2]]
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[I]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP]], label %[[EXIT_BLOCK:.*]]
; CHECK:       [[EXIT_BLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]

  ; External function may modify memory.
  call void @external_function(ptr %arr)

  %gep1 = getelementptr float, ptr %arr, i32 %i
  %load1 = load float, ptr %gep1
  %sext = sext i32 %min.idx to i64
  %gep2 = getelementptr float, ptr %arr, i64 %sext
  %gep3 = getelementptr i8, ptr %gep2, i64 0
  %load2 = load float, ptr %gep3
  %cmp = fcmp olt float %load1, %load2
  %sel = select i1 %cmp, float %load1, float %load2
  %min.idx.next = select i1 %cmp, i32 %i, i32 %min.idx
  %i.next = add i32 %i, 1
  %exit = icmp slt i32 %i.next, %n
  br i1 %exit, label %loop, label %exit_block

exit_block:
  ret void
}

; Negative test: byte offsets on the two load addresses do not satisfy
; bytes_offset(val.first.gep) - bytes_offset(val.min.gep)
;   == sizeof(LoadType) * step_of_iv_next
; Here val.first has no i8-offset (C1 = 0), val.min has -4 (C2 = -4),
; sizeof(float) = 4, and step = -1, so the required equality
; (C1 - C2 == sizeof(T) * step) becomes 4 == -4 -- false. Transforming
; would propagate this iter's val.first as next iter's known_min, but
; next iter's val.min reads a different address. Recognizer must bail.
define i32 @test_gvn_min_pattern_offset_mismatch(ptr %base) {
; CHECK-LABEL: define i32 @test_gvn_min_pattern_offset_mismatch(
; CHECK-SAME: ptr [[BASE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CTR:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[CTR_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MIN_IDX:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[MIN_IDX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], -1
; CHECK-NEXT:    [[PTR_IV:%.*]] = getelementptr float, ptr [[BASE]], i64 [[IV]]
; CHECK-NEXT:    [[VAL_FIRST:%.*]] = load float, ptr [[PTR_IV]], align 4
; CHECK-NEXT:    [[MIN_IDX_EXT:%.*]] = sext i32 [[MIN_IDX]] to i64
; CHECK-NEXT:    [[GEP_TYPED:%.*]] = getelementptr float, ptr [[BASE]], i64 [[MIN_IDX_EXT]]
; CHECK-NEXT:    [[GEP_OFFSET:%.*]] = getelementptr i8, ptr [[GEP_TYPED]], i64 -4
; CHECK-NEXT:    [[VAL_MIN:%.*]] = load float, ptr [[GEP_OFFSET]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[VAL_FIRST]], [[VAL_MIN]]
; CHECK-NEXT:    [[NEW_IDX:%.*]] = trunc nsw i64 [[IV_NEXT]] to i32
; CHECK-NEXT:    [[MIN_IDX_NEXT]] = select i1 [[CMP]], i32 [[NEW_IDX]], i32 [[MIN_IDX]]
; CHECK-NEXT:    [[CTR_NEXT]] = add nsw i64 [[CTR]], -1
; CHECK-NEXT:    [[COND:%.*]] = icmp samesign ugt i64 [[CTR]], 1
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[MIN_IDX_NEXT]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 3, %entry ], [ %iv.next, %loop ]
  %ctr = phi i64 [ 3, %entry ], [ %ctr.next, %loop ]
  %min.idx = phi i32 [ 1, %entry ], [ %min.idx.next, %loop ]
  %iv.next = add nsw i64 %iv, -1
  %ptr.iv = getelementptr float, ptr %base, i64 %iv
  %val.first = load float, ptr %ptr.iv, align 4
  %min.idx.ext = sext i32 %min.idx to i64
  %gep.typed = getelementptr float, ptr %base, i64 %min.idx.ext
  %gep.offset = getelementptr i8, ptr %gep.typed, i64 -4
  %val.min = load float, ptr %gep.offset, align 4
  %cmp = fcmp olt float %val.first, %val.min
  %new.idx = trunc nsw i64 %iv.next to i32
  %min.idx.next = select i1 %cmp, i32 %new.idx, i32 %min.idx
  %ctr.next = add nsw i64 %ctr, -1
  %cond = icmp samesign ugt i64 %ctr, 1
  br i1 %cond, label %loop, label %exit

exit:
  ret i32 %min.idx.next
}
