; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=loongarch64-unknown-linux-gnu -O2 < %s -verify-machineinstrs | FileCheck %s -check-prefix=LA64
; RUN: llc -mtriple=loongarch32-unknown-linux-gnu -O2 < %s -verify-machineinstrs | FileCheck %s -check-prefix=LA32

; Tests copied from PowerPC.

; Free probe
define i8 @f0() #0 nounwind {
;
; LA64-LABEL: f0:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    addi.d $sp, $sp, -80
; LA64-NEXT:    ori $a0, $zero, 3
; LA64-NEXT:    st.b $a0, $sp, 16
; LA64-NEXT:    ld.b $a0, $sp, 16
; LA64-NEXT:    addi.d $sp, $sp, 80
; LA64-NEXT:    ret
;
; LA32-LABEL: f0:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    addi.w $sp, $sp, -64
; LA32-NEXT:    ori $a0, $zero, 3
; LA32-NEXT:    st.b $a0, $sp, 0
; LA32-NEXT:    ld.b $a0, $sp, 0
; LA32-NEXT:    addi.w $sp, $sp, 64
; LA32-NEXT:    ret
entry:
  %a = alloca i8, i64 64
  %b = getelementptr inbounds i8, ptr %a, i64 63
  store volatile i8 3, ptr %a
  %c = load volatile i8, ptr %a
  ret i8 %c
}

define i8 @f1() #0 nounwind {
;
; LA64-LABEL: f1:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    lu12i.w $a0, 1
; LA64-NEXT:    sub.d $sp, $sp, $a0
; LA64-NEXT:    st.d $zero, $sp, 0
; LA64-NEXT:    addi.d $sp, $sp, -16
; LA64-NEXT:    ori $a0, $zero, 3
; LA64-NEXT:    st.b $a0, $sp, 16
; LA64-NEXT:    ld.b $a0, $sp, 16
; LA64-NEXT:    lu12i.w $a1, 1
; LA64-NEXT:    ori $a1, $a1, 16
; LA64-NEXT:    add.d $sp, $sp, $a1
; LA64-NEXT:    ret
;
; LA32-LABEL: f1:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    lu12i.w $a0, 1
; LA32-NEXT:    sub.w $sp, $sp, $a0
; LA32-NEXT:    st.w $zero, $sp, 0
; LA32-NEXT:    addi.w $sp, $sp, -16
; LA32-NEXT:    ori $a0, $zero, 3
; LA32-NEXT:    st.b $a0, $sp, 16
; LA32-NEXT:    ld.b $a0, $sp, 16
; LA32-NEXT:    lu12i.w $a1, 1
; LA32-NEXT:    ori $a1, $a1, 16
; LA32-NEXT:    add.w $sp, $sp, $a1
; LA32-NEXT:    ret
entry:
  %a = alloca i8, i64 4096
  %b = getelementptr inbounds i8, ptr %a, i64 63
  store volatile i8 3, ptr %a
  %c = load volatile i8, ptr %a
  ret i8 %c
}

define i8 @f2() #0 nounwind {
;
; LA64-LABEL: f2:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    lu12i.w $a0, 16
; LA64-NEXT:    sub.d $t1, $sp, $a0
; LA64-NEXT:    lu12i.w $t2, 1
; LA64-NEXT:  .LBB2_1: # %entry
; LA64-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64-NEXT:    sub.d $sp, $sp, $t2
; LA64-NEXT:    st.d $zero, $sp, 0
; LA64-NEXT:    bne $sp, $t1, .LBB2_1
; LA64-NEXT:  # %bb.2: # %entry
; LA64-NEXT:    addi.d $sp, $sp, -16
; LA64-NEXT:    ori $a0, $zero, 3
; LA64-NEXT:    st.b $a0, $sp, 16
; LA64-NEXT:    ld.b $a0, $sp, 16
; LA64-NEXT:    lu12i.w $a1, 16
; LA64-NEXT:    ori $a1, $a1, 16
; LA64-NEXT:    add.d $sp, $sp, $a1
; LA64-NEXT:    ret
;
; LA32-LABEL: f2:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    lu12i.w $a0, 16
; LA32-NEXT:    sub.w $t1, $sp, $a0
; LA32-NEXT:    lu12i.w $t2, 1
; LA32-NEXT:  .LBB2_1: # %entry
; LA32-NEXT:    # =>This Inner Loop Header: Depth=1
; LA32-NEXT:    sub.w $sp, $sp, $t2
; LA32-NEXT:    st.w $zero, $sp, 0
; LA32-NEXT:    bne $sp, $t1, .LBB2_1
; LA32-NEXT:  # %bb.2: # %entry
; LA32-NEXT:    addi.w $sp, $sp, -16
; LA32-NEXT:    ori $a0, $zero, 3
; LA32-NEXT:    st.b $a0, $sp, 16
; LA32-NEXT:    ld.b $a0, $sp, 16
; LA32-NEXT:    lu12i.w $a1, 16
; LA32-NEXT:    ori $a1, $a1, 16
; LA32-NEXT:    add.w $sp, $sp, $a1
; LA32-NEXT:    ret
entry:
  %a = alloca i8, i64 65536
  %b = getelementptr inbounds i8, ptr %a, i64 63
  store volatile i8 3, ptr %a
  %c = load volatile i8, ptr %a
  ret i8 %c
}

define i8 @f3() #0 "stack-probe-size"="32768" nounwind {
;
; LA64-LABEL: f3:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    lu12i.w $a0, 8
; LA64-NEXT:    sub.d $sp, $sp, $a0
; LA64-NEXT:    st.d $zero, $sp, 0
; LA64-NEXT:    lu12i.w $a0, 8
; LA64-NEXT:    sub.d $sp, $sp, $a0
; LA64-NEXT:    st.d $zero, $sp, 0
; LA64-NEXT:    addi.d $sp, $sp, -16
; LA64-NEXT:    ori $a0, $zero, 3
; LA64-NEXT:    st.b $a0, $sp, 16
; LA64-NEXT:    ld.b $a0, $sp, 16
; LA64-NEXT:    lu12i.w $a1, 16
; LA64-NEXT:    ori $a1, $a1, 16
; LA64-NEXT:    add.d $sp, $sp, $a1
; LA64-NEXT:    ret
;
; LA32-LABEL: f3:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    lu12i.w $a0, 8
; LA32-NEXT:    sub.w $sp, $sp, $a0
; LA32-NEXT:    st.w $zero, $sp, 0
; LA32-NEXT:    lu12i.w $a0, 8
; LA32-NEXT:    sub.w $sp, $sp, $a0
; LA32-NEXT:    st.w $zero, $sp, 0
; LA32-NEXT:    addi.w $sp, $sp, -16
; LA32-NEXT:    ori $a0, $zero, 3
; LA32-NEXT:    st.b $a0, $sp, 16
; LA32-NEXT:    ld.b $a0, $sp, 16
; LA32-NEXT:    lu12i.w $a1, 16
; LA32-NEXT:    ori $a1, $a1, 16
; LA32-NEXT:    add.w $sp, $sp, $a1
; LA32-NEXT:    ret
entry:
  %a = alloca i8, i64 65536
  %b = getelementptr inbounds i8, ptr %a, i64 63
  store volatile i8 3, ptr %a
  %c = load volatile i8, ptr %a
  ret i8 %c
}

; Same as f2, but without protection.
define i8 @f4() nounwind {
;
; LA64-LABEL: f4:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    lu12i.w $a0, 16
; LA64-NEXT:    ori $a0, $a0, 16
; LA64-NEXT:    sub.d $sp, $sp, $a0
; LA64-NEXT:    ori $a0, $zero, 3
; LA64-NEXT:    st.b $a0, $sp, 16
; LA64-NEXT:    ld.b $a0, $sp, 16
; LA64-NEXT:    lu12i.w $a1, 16
; LA64-NEXT:    ori $a1, $a1, 16
; LA64-NEXT:    add.d $sp, $sp, $a1
; LA64-NEXT:    ret
;
; LA32-LABEL: f4:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    lu12i.w $a0, 16
; LA32-NEXT:    ori $a0, $a0, 16
; LA32-NEXT:    sub.w $sp, $sp, $a0
; LA32-NEXT:    ori $a0, $zero, 3
; LA32-NEXT:    st.b $a0, $sp, 16
; LA32-NEXT:    ld.b $a0, $sp, 16
; LA32-NEXT:    lu12i.w $a1, 16
; LA32-NEXT:    ori $a1, $a1, 16
; LA32-NEXT:    add.w $sp, $sp, $a1
; LA32-NEXT:    ret
entry:
  %a = alloca i8, i64 65536
  %b = getelementptr inbounds i8, ptr %a, i64 63
  store volatile i8 3, ptr %a
  %c = load volatile i8, ptr %a
  ret i8 %c
}

define i8 @f5() #0 "stack-probe-size"="65536" nounwind {
;
; LA64-LABEL: f5:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    lu12i.w $a0, 256
; LA64-NEXT:    sub.d $t1, $sp, $a0
; LA64-NEXT:    lu12i.w $t2, 16
; LA64-NEXT:  .LBB5_1: # %entry
; LA64-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64-NEXT:    sub.d $sp, $sp, $t2
; LA64-NEXT:    st.d $zero, $sp, 0
; LA64-NEXT:    bne $sp, $t1, .LBB5_1
; LA64-NEXT:  # %bb.2: # %entry
; LA64-NEXT:    addi.d $sp, $sp, -16
; LA64-NEXT:    ori $a0, $zero, 3
; LA64-NEXT:    st.b $a0, $sp, 16
; LA64-NEXT:    ld.b $a0, $sp, 16
; LA64-NEXT:    lu12i.w $a1, 256
; LA64-NEXT:    ori $a1, $a1, 16
; LA64-NEXT:    add.d $sp, $sp, $a1
; LA64-NEXT:    ret
;
; LA32-LABEL: f5:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    lu12i.w $a0, 256
; LA32-NEXT:    sub.w $t1, $sp, $a0
; LA32-NEXT:    lu12i.w $t2, 16
; LA32-NEXT:  .LBB5_1: # %entry
; LA32-NEXT:    # =>This Inner Loop Header: Depth=1
; LA32-NEXT:    sub.w $sp, $sp, $t2
; LA32-NEXT:    st.w $zero, $sp, 0
; LA32-NEXT:    bne $sp, $t1, .LBB5_1
; LA32-NEXT:  # %bb.2: # %entry
; LA32-NEXT:    addi.w $sp, $sp, -16
; LA32-NEXT:    ori $a0, $zero, 3
; LA32-NEXT:    st.b $a0, $sp, 16
; LA32-NEXT:    ld.b $a0, $sp, 16
; LA32-NEXT:    lu12i.w $a1, 256
; LA32-NEXT:    ori $a1, $a1, 16
; LA32-NEXT:    add.w $sp, $sp, $a1
; LA32-NEXT:    ret
entry:
  %a = alloca i8, i64 1048576
  %b = getelementptr inbounds i8, ptr %a, i64 63
  store volatile i8 3, ptr %a
  %c = load volatile i8, ptr %a
  ret i8 %c
}

define i8 @f6() #0 nounwind {
;
; LA64-LABEL: f6:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    lu12i.w $a0, 262144
; LA64-NEXT:    sub.d $t1, $sp, $a0
; LA64-NEXT:    lu12i.w $t2, 1
; LA64-NEXT:  .LBB6_1: # %entry
; LA64-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64-NEXT:    sub.d $sp, $sp, $t2
; LA64-NEXT:    st.d $zero, $sp, 0
; LA64-NEXT:    bne $sp, $t1, .LBB6_1
; LA64-NEXT:  # %bb.2: # %entry
; LA64-NEXT:    addi.d $sp, $sp, -16
; LA64-NEXT:    ori $a0, $zero, 3
; LA64-NEXT:    st.b $a0, $sp, 16
; LA64-NEXT:    ld.b $a0, $sp, 16
; LA64-NEXT:    lu12i.w $a1, 262144
; LA64-NEXT:    ori $a1, $a1, 16
; LA64-NEXT:    add.d $sp, $sp, $a1
; LA64-NEXT:    ret
;
; LA32-LABEL: f6:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    lu12i.w $a0, 262144
; LA32-NEXT:    sub.w $t1, $sp, $a0
; LA32-NEXT:    lu12i.w $t2, 1
; LA32-NEXT:  .LBB6_1: # %entry
; LA32-NEXT:    # =>This Inner Loop Header: Depth=1
; LA32-NEXT:    sub.w $sp, $sp, $t2
; LA32-NEXT:    st.w $zero, $sp, 0
; LA32-NEXT:    bne $sp, $t1, .LBB6_1
; LA32-NEXT:  # %bb.2: # %entry
; LA32-NEXT:    addi.w $sp, $sp, -16
; LA32-NEXT:    ori $a0, $zero, 3
; LA32-NEXT:    st.b $a0, $sp, 16
; LA32-NEXT:    ld.b $a0, $sp, 16
; LA32-NEXT:    lu12i.w $a1, 262144
; LA32-NEXT:    ori $a1, $a1, 16
; LA32-NEXT:    add.w $sp, $sp, $a1
; LA32-NEXT:    ret
entry:
  %a = alloca i8, i64 1073741824
  %b = getelementptr inbounds i8, ptr %a, i64 63
  store volatile i8 3, ptr %a
  %c = load volatile i8, ptr %a
  ret i8 %c
}

define i8 @f7() #0 "stack-probe-size"="65536" nounwind {
;
; LA64-LABEL: f7:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    lu12i.w $a0, 244128
; LA64-NEXT:    sub.d $t1, $sp, $a0
; LA64-NEXT:    lu12i.w $t2, 16
; LA64-NEXT:  .LBB7_1: # %entry
; LA64-NEXT:    # =>This Inner Loop Header: Depth=1
; LA64-NEXT:    sub.d $sp, $sp, $t2
; LA64-NEXT:    st.d $zero, $sp, 0
; LA64-NEXT:    bne $sp, $t1, .LBB7_1
; LA64-NEXT:  # %bb.2: # %entry
; LA64-NEXT:    lu12i.w $a0, 12
; LA64-NEXT:    ori $a0, $a0, 2576
; LA64-NEXT:    sub.d $sp, $sp, $a0
; LA64-NEXT:    ori $a0, $zero, 3
; LA64-NEXT:    st.b $a0, $sp, 9
; LA64-NEXT:    ld.b $a0, $sp, 9
; LA64-NEXT:    lu12i.w $a1, 244140
; LA64-NEXT:    ori $a1, $a1, 2576
; LA64-NEXT:    add.d $sp, $sp, $a1
; LA64-NEXT:    ret
;
; LA32-LABEL: f7:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    lu12i.w $a0, 244128
; LA32-NEXT:    sub.w $t1, $sp, $a0
; LA32-NEXT:    lu12i.w $t2, 16
; LA32-NEXT:  .LBB7_1: # %entry
; LA32-NEXT:    # =>This Inner Loop Header: Depth=1
; LA32-NEXT:    sub.w $sp, $sp, $t2
; LA32-NEXT:    st.w $zero, $sp, 0
; LA32-NEXT:    bne $sp, $t1, .LBB7_1
; LA32-NEXT:  # %bb.2: # %entry
; LA32-NEXT:    lu12i.w $a0, 12
; LA32-NEXT:    ori $a0, $a0, 2576
; LA32-NEXT:    sub.w $sp, $sp, $a0
; LA32-NEXT:    ori $a0, $zero, 3
; LA32-NEXT:    st.b $a0, $sp, 9
; LA32-NEXT:    ld.b $a0, $sp, 9
; LA32-NEXT:    lu12i.w $a1, 244140
; LA32-NEXT:    ori $a1, $a1, 2576
; LA32-NEXT:    add.w $sp, $sp, $a1
; LA32-NEXT:    ret
entry:
  %a = alloca i8, i64 1000000007
  %b = getelementptr inbounds i8, ptr %a, i64 101
  store volatile i8 3, ptr %a
  %c = load volatile i8, ptr %a
  ret i8 %c
}

attributes #0 = { "probe-stack"="inline-asm" }
